// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // The CLI (db push / migrate) needs a direct, session-scoped connection —
  // Supabase's transaction-mode pooler (DATABASE_URL, used by the app at
  // runtime via src/lib/db.ts) doesn't support the session state Migrate
  // relies on and just hangs. DIRECT_URL is the non-pooled connection.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
